[POST /map] add response
MySpooot/MySpot-Backend pull request #106
Opened 2022-03-31 15:03 UTC by InJaEE

2022-03-31 15:42 UTC, 2-chanhee requested changes
pr리뷰 어려워요

2022-03-31 15:42 UTC, 2-chanhee commented on src/map/map.service.ts
> +        const createdMap = await this.connection.getRepository(Map).findOne({ where: { id: insertMap.generatedMaps[0].id } });
const createdMap = await this.connection.getRepository(Map).findOne({ id: insertMap.generatedMaps[0].id });
조건절에 where 안쓰고 이렇게만 해도 됩니다

2022-03-31 15:42 UTC, 2-chanhee commented on src/map/dto/post_user_map.dto.ts
> +}
mapName이랑 isPrivate도 프론트에서 사용하나요?
회의록에선 맵 생성 후 해당 map으로 이동한다고만 써있어서 id만 필요한게 아닌가 싶습니다

2022-03-31 15:42 UTC, 2-chanhee commented on src/map/dto/post_user_map.dto.ts
> +import { Map } from '../../entities/map.entity';
2라인과 3라인  개행 부탁드립니다

외부모듈, 내부모듈 개행으로 분리하고 있습니다.

2022-03-31 15:42 UTC, 2-chanhee commented on src/map/map.controller.spec.ts
> +            expect(result).toBeDefined();
단순히 accessible mock data를 생성한 것이기 때문에 toBeDefined()를 하지 않아도 될 듯 합니다. 기존 코드 유지해도 될거같아요

2022-03-31 15:42 UTC, 2-chanhee commented on src/map/map.controller.spec.ts
> +            expect(result).toBeDefined();
response가 기존엔 없었다가 추가되었지만 테스트에서 그걸 검증하는 부분은 없는 듯 합니다.
api 콜의 결과를 담는 변수를 선언하고, 그 변수에 response에 들어가야 할 값들이 제대로 들어가나 테스트하는 부분이 필요합니다.

2022-03-31 15:47 UTC, 2-chanhee commented on src/map/map.controller.spec.ts
> +            expect(result).toBeDefined();
아 그리고 컨트롤러에 @ApiOkResponse() 확인해보시면 여기에 response type을 선언해줘야 합니다. 
그래야 스웨거에 타입이 나오기 때문에 다른 곳들 보고 그냥 추가해주시면 될 것 같아요

2022-03-31 16:08 UTC, InJaEE commented on src/map/dto/post_user_map.dto.ts
> +}
걍 무지성 다 보낼까했는데 삭제해야겠군요 ㅋㅋ

2022-03-31 16:08 UTC, InJaEE commented on src/map/map.controller.spec.ts
> +            expect(result).toBeDefined();
제대로 수정한건진 모르겠지만 수정하였습니다 ㅋㅋ

2022-03-31 16:09 UTC, InJaEE commented on src/map/map.service.ts
> +        const createdMap = await this.connection.getRepository(Map).findOne({ where: { id: insertMap.generatedMaps[0].id } });
근ㄷ ㅔ이거 insert의 결과로 return하는 방법은 없나요?

2022-03-31 16:26 UTC, 2-chanhee requested changes
리뷰2

2022-03-31 16:26 UTC, 2-chanhee commented on src/map/map.controller.spec.ts
> +            expect(result).toEqual({ id: data.at(-1).id + 1 });
비교가 잘못된 것 같습니다.
result에서 return해주는 id는 accessible의 id가 아닙니다.
테스트 케이스마다 데이터베이스를 초기화하기 떄문에 생성한 map과 accessible의 id가 일치해서 테스트에 통과한 것으로 보입니다. 

정확하게 하려면
1. expect(result).toEqual({ id: data.at(-1).map_id + 1 }); 
2. expect(result).toEqual({ id: maps.at(-1).id + 1 });
가 맞는 건데 

서비스 코드를 보면 map의 id를 return해주고 있으므로 1번으로 하는게 정확한 테스트 코드인 것 같습니다

2022-03-31 16:26 UTC, 2-chanhee commented on src/map/map.controller.spec.ts
> +            expect(result).toEqual({ id: data.at(-1).id + 1 });
그리고 컨트롤러에 아까 말씀드린 ApiOkResponse 데코레이터에 response type 추가 부탁드립니다. 
추가 안하면 스웨거에 정상적으로 나오지 않습니다

2022-03-31 16:46 UTC, 2-chanhee commented on src/map/map.controller.spec.ts
> +            expect(result).toEqual({ id: data.at(-1).id + 1 });
Map 테이블에서 마지막 id에서 +1 해주는게.. 네 말씀하신게 맞습니다

2022-03-31 16:47 UTC, 2-chanhee commented on src/map/map.controller.spec.ts
> +            expect(result).toEqual({ id: data.at(-1).id + 1 });
리뷰쓸때 1번이 맞다고 썼다가 잘못써가지구 2번이 맞다고 업데이트했는데 반영이 안되었나.,.ㅋㅋㅋ map에서 id+1 해서 비교하는 게 정확한 것 같아요

2022-03-31 16:52 UTC, 2-chanhee requested changes
리부ㅠ3

2022-03-31 16:52 UTC, 2-chanhee commented on src/map/map.controller.ts
> +    @ApiOkResponse({ type: [PostUserMapResponse] })
리스폰스가 배열 타입이 아니므로 [] 제거해야 합니다

2022-03-31 16:52 UTC, 2-chanhee commented on src/map/map.controller.spec.ts
> +            expect(result).toEqual({ id: ++maps.at(-1).id });
화긴완료
이거 리뷰 달아놓고 request change 이후 수정하면 반영이 안되나요? 
accessible이 맞다고 잘못써서 다시 map이 맞다고 바꿨는데 ㅋㅋ ㅋ여튼 map으로 비교하는게 더 좋은 것 같슴다 굳

2022-04-01 00:48 UTC, InJaEE commented on src/map/map.controller.ts
> +    @ApiOkResponse({ type: [PostUserMapResponse] })
완료 ㅎ

2022-04-01 01:06 UTC, merged